language: swift
osx_image: xcode9.3beta
xcode_workspace: brewdog.xcworkspace
xcode_scheme: brewdogTests
before_install:
install:
script:
- xcodebuild -workspace brewdog.xcworkspace -list
- xcodebuild -workspace brewdog.xcworkspace -scheme brewdog -sdk iphonesimulator
  -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.4'
  GCC_GENERATE_TEST_COVERAGE_FILES=YES build test
after_success:
- bash <(curl -s https://codecov.io/bash)
